### ISSUE TITLE
To-Do List of the project 

### ISSUE THREAD

**Issue by Samuel-Scalbert** [Samuel-Scalbert/Project-LOL#1]
Hello everyone,

As I started this project in English I think it is only logical to keep speaking in English. Also, I just started the product registration and so someone is going to check our work. Below this issue, I'm going to create the first to-do list to keep track of the project, feel free to add what you want to do in the app. 

Be aware the repo is now public for LOL to check the project.

actors: @MaevaTarantini / @arlequinte / @Samuel-Scalbert 

### 1. Initialization of the project 

- [x] Check if we are allowed to do our project on the API of LOL
- [x] Registration of the product on [(https://developer.riotgames.com/)]
- [x] First preliminary work on the API to test the API
- [ ] Pre-production phase and delimitation of all the functions available in our project

When we have all the functions we want in our project we can then get on the coding of all of them. I would advise you to test them on a python notebook.

### 2. Functions by actors

@Samuel-Scalbert: my main focus is on the SOLO Q essentially

- [ ] login function for the visitors ( to keep track of a list of accounts that they want to follow)
- [ ] a leaderboard only with the list of accounts you want to track
- [ ] the win rate for each day for your account  
- [ ] a graph to show the LP loss/win (for the week)

@MaevaTarantini 
@arlequinte 

functions ideas :

- a tab that summarizes the exp gain for the mastery of your champ
- here you can add any ideas that you feel are interesting to implement 

### 3. Flask application 

When we get to this part, it will mean that we have finished practically all of our functions. As I am (@Samuel-Scalbert) a bit ahead I will start early in this phase to correct any bugs that could occur. 

- [ ] design of the app
- [ ] checking phase of the functions we created 
- [ ] production of the Flask app
